"use client";
import Link from "next/link";
import { BookOpen, ChevronsUpDown, LogOut, Menu, Search, Users } from "lucide-react";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { useAuth } from "./auth-provider";
function Brand(){return <Link href="/courses" className="flex items-center gap-3 text-lg font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-lg bg-emerald-700 text-white">T</span>Tella Admin</Link>}
function Nav({permissions}:{permissions:string[]}){const pathname=usePathname();const item=(href:string,label:string,icon:React.ReactNode)=><Link href={href} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${pathname.startsWith(href)?"bg-emerald-50 text-emerald-900":"text-muted-foreground hover:bg-muted"}`}>{icon}{label}</Link>;return <nav aria-label="Primary" className="mt-10 space-y-5"><div><p className="mb-2 px-3 text-[11px] font-semibold uppercase tracking-[.16em] text-muted-foreground">Content</p>{item("/courses","Courses",<BookOpen className="size-4"/>)}</div>{permissions.includes("students.view_studentgroup")&&<div><p className="mb-2 px-3 text-[11px] font-semibold uppercase tracking-[.16em] text-muted-foreground">Learners</p>{item("/student-groups","Student groups",<Users className="size-4"/>)}</div>}</nav>}
export function AdminShell({children}:{children:React.ReactNode}){const{user,loading,logout}=useAuth();const[open,setOpen]=useState(false);if(loading)return <div className="grid min-h-screen place-items-center text-sm text-muted-foreground" role="status">Loading workspace…</div>;if(!user)return null;return <div className="min-h-screen bg-[#f7f8f5] text-[#17211b]"><aside className="fixed inset-y-0 left-0 hidden w-60 border-r bg-white px-5 py-6 lg:block"><Brand/><Nav permissions={user.permissions}/><div className="absolute inset-x-5 bottom-5 border-t pt-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#173e2c] text-xs font-bold text-white">{user.display_name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{user.display_name}</p><p className="truncate text-[10px] text-muted-foreground">{user.groups.join(", ")}</p></div><Button size="icon-sm" variant="ghost" aria-label="Log out" onClick={logout}><LogOut/></Button></div></div></aside><div className="lg:pl-60"><header className="sticky top-0 z-20 flex h-16 items-center gap-3 border-b bg-white/90 px-4 backdrop-blur md:px-7"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger render={<Button size="icon" variant="ghost" className="lg:hidden" aria-label="Open navigation"/>}><Menu/></SheetTrigger><SheetContent side="left" className="w-64 p-6"><SheetTitle className="sr-only">Navigation</SheetTitle><Brand/><Nav permissions={user.permissions}/></SheetContent></Sheet><div className="relative hidden max-w-md flex-1 md:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input className="h-9 w-full rounded-lg bg-muted/60 pl-9 pr-3 text-xs outline-none ring-emerald-700 focus:ring-2" placeholder="Search workspace…" aria-label="Search workspace"/></div><div className="ml-auto flex items-center gap-2 text-xs text-muted-foreground">{user.display_name}<ChevronsUpDown className="size-3"/></div></header>{children}</div></div>}
